"use strict";
exports.__esModule = true;
exports.DialogTheme = exports.BDialogContent = exports.BDialog = void 0;
var BDialog_1 = require("./BDialog");
exports.BDialog = BDialog_1["default"];
var BDialogContent_1 = require("./BDialogContent");
exports.BDialogContent = BDialogContent_1["default"];
var theme_1 = require("./theme");
exports.DialogTheme = theme_1.DialogTheme;
exports["default"] = BDialog_1["default"];
